const time = [
  'on a rainy day',
  'before tucking into bed',
  'first thing in the morning',
  'on the weekend',
  'on wednesday',
  'in the morning',
  'before you sleep',
  'next time you have a break',
  'at the end of the day',
  'after school',
  'after dinner',
  'after lunch',
  'before breakfast',
  'when the sun goes down',
  'during the sunrise',
  'after your bills arrive',
  'when you feel energetic',
  'next time you see your neighbour',
  'after your curfew',
  'tomorrow',
];

const actionGrounded = [
  'open your window',
  'say your joys and frustrations out loud',
  'walk to the supermarket',
  'narrate what your are doing',
  'call a friend',
  'do some washing',
  'ask the person closest to you for a massage',
  'wash your hands',
  'wash your feet',
  'draw a small idea',
  'set up the percolator',
  'take a cold shower',
  'bake something tasty',
  'play a board game',
  'for an explorative walk',
  'take a hot shower',
  'write a journal entry',
  'change clothes',
  'put on fresh socks',
  'vacuum your favourite room',
  'apply tiger balm',
  'masturbate',
  'rearrange some furniture',
  'moisturise your entire body',
  'roll a joint',
];

const senses = {
  sight: {
    verbs: [
      'staring intensely at',
      'looking at',
      'watching',
      'squinting your eyes and looking at',
      'fluttering your eyelashes and staring at',
    ],
    nouns: [
      'yourself in the mirror',
      'a lamp',
      'something out the window',
      'a friend',
      'what lies under the nearest rock',
      'warm lights',
      'a source of natural light',
      'planes',
      'flight radar 24',
      'sunshine',
      'people enjoying local cafes',
      'your eyelids',
      'a piece of artwork',
      'stained glass',
      'a tram',
      'train station',
      'your neighbours',
    ],
  },
  smell: {
    verbs: [
      'filling your nostrils with the scent of',
      'sniffing',
      'burning and inhaling the fumes of',
      'smelling',
      'enjoying the aroma of',
      'taking a deep whiff of',
    ],
    nouns: [
      'incense',
      'citrus',
      'vanilla essence',
      'strawberries',
      'a sprig of lavender',
      'lavender oil',
      'lemongrass oil',
      'orange zest',
      'cardamom coffee',
      'old books',
      'stolen flowers',
      'grass',
      'szechuan chilli',
      'tiger balm',
      'fresh rosemary',
      'jasmine tea',
      'pine',
      'some pencil shavings',
      'a newspaper',
      'marijuana',
      'scented candles',
      'flowers',
      'fresh air',
      'freshly roasted coffee',
      'essential oils',
    ],
  },
  sound: {
    verbs: [
      'focusing your hearing on',
      'putting on noise cancelling headphones and listening to',
      'starting a spotify radio with ',
      'listening to',
    ],
    nouns: [
      'birds chirping',
      'afrobeats',
      'ambient noise',
      'birds chirping',
      'sounds of the wind',
      'afrobeats',
      'reggaeton',
      'lo-fi beats',
      'a podcast',
      'bluegrass',
      'a cats purr',
      'the sounds of a banjo',
      'the sound of cars on the road',
    ],
  },
  taste: {
    verbs: [
      'consuming',
      'nestling your face into',
      'tasting',
      'filling your mouth with',
      'savouring the taste of',
    ],
    nouns: [
      'coffee',
      'citrus jam',
      'jasmine tea',
      'sourdough bread',
      'olives',
      'cardamom coffee',
      'a mix of peppermint and black tea',
      'citrus',
      'toothpaste',
      'milky earl grey tea',
      'a pickle',
      'stonefruit',
      'coffee',
      'instant miso soup',
      'minty chocolate',
      'kombucha',
      'rice crackers',
      'a dash of rose water',
      'a mandarin',
      'iced green tea',
    ],
  },
  touch: {
    verbs: [
      'burying your nails into',
      'carefully touching',
      'touching',
      'feeling the texture of',
      'grabing and holding',
      'rubbing your cheek on',
    ],
    nouns: [
      'something spiky',
      'slightly damp grass',
      'unmowed grass',
      'some pebbles',
      'a wheat bag',
      'grass',
      'something warm',
      'sunrays',
      'a soft blanket',
      'a cool fresh sheet',
      'the softest part of your skin',
      'something knitted',
      'the skin of a fruit',
      'a cool mug',
      'toilet paper',
      'crayons',
      'a really nice leaf',
    ],
  },
}

const actionAscended = [
  'embody the spirit of',
  'become',
  'transform into',
  'turn yourself into',
  'emerge as',
  'convert yourself into',
  'metamorphose into',
];

const body = [
  'a butterfly with colourful wings',
  'a prickly cactus',
  'a crunchy autumn leaf',
  'a rabbit',
  'a small dog',
  'an atom',
  'a kite',
  'a remote control',
  'a drone',
  'a raindrop',
  'a ball of fire',
  'a mug',
  'an onion',
  'a pickle',
  'a rotten apple',
  'a woven basket',
  'a security camera',
  'a candlestick',
  'a skeleton',
  'a sound wave',
  'a bolt of lightning',
  'a wick of a flame',
  'a grain of wild rice',
  'a little ladybug',
  'a piece of debris',
  'a lost item at baggage claim',
  'a pearl necklace',
  'an eraser',
  'a masculine cat',
  'a letter tile from a pictionary set',
  'a light bulb',
  'a gingerbread person',
  'a hammer',
  'a magic blanket',
  'a brick',
  'bob ross',
];

const activity = [
  'walking around',
  'flying',
  'singing',
  'jumping around',
  'relaxing',
  'figure skating',
  'posing for a photo',
  'telling ghost stories',
  'drinking a thickshake',
  'speaking jiberish',
  'drinking wine',
  'eating an apple',
  'skating',
  'crawling',
  'driving a mystery bus',
  'breathing through a snorkel',
  'walking along',
  'building a snowperson',
  'trying on hats',
  'sippin coffee',
  'counting cards',
  'collecting stamps',
  'experienceing pins and needles',
  'combing a friends hair',
  'playing poker',
  'laying bricks',
  'painting on canvas',
  'wearing a beret',
  'heading towards the sun',
  'eating pineapple sorbet',
  'mushroom picking',
  'peeling grapes',
  'hiding from someone',
  'floating with the river current',
];

const scene = [
  'in a parallel universe',
  'in a vampire theme park',
  'in a milkyway',
  'inside a shipwreck',
  'in field of flowers',
  'on the horizon',
  'on a cloud',
  'on mars',
  'deep in the ocean',
  'inside a banana peel',
  'inside your computer screen',
  'inside a whales stomach',
  'in a world with reverse gravity',
  'in a desert landscape',
  'inside a jar of olives',
  'in a world depicted by picasso',
  'in a police car',
  'in the year 2121',
  'on a rainbow',
  'in a hover-skate park',
  'inside a teapot',
  'on top of a brick wall',
  'inside a mouth',
  'inside a rubbish bin',
  'inside a bubble',
  'in a courtroom',
  'inside a vending machine',
  'in the mountains',
  'under a conference table',
  'inside a space station',
  'in a really good hiding place',
];

export const getRandom = (list: any[]) => list[Math.floor(Math.random() * list.length)]

export const getGrounded = (sense1: string, sense2: string) => getGroundedCustom(actionGrounded, sense1, sense2);

export const getGroundedCustom = (actions: any[], sense1: string, sense2: string) => `${getRandom(time)}, ${getRandom(actions)} while ${getRandom(senses[sense1].verbs)} ${getRandom(senses[sense1].nouns)} and ${getRandom(senses[sense2].verbs)} ${getRandom(senses[sense2].nouns)}`;

export const getAscended = () => `${getRandom(actionAscended)} ${getRandom(body)} while ${getRandom(activity)} ${getRandom(scene)}`;
